---
version: "2"
services:
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile-prometheus
    ports:
      - 9090:9090
    links:
      - pushgateway
